services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Registro explícito del servicio base
    App\Service\BasicMessageService:
        class: App\Service\BasicMessageService


    App\Service\SmsDecoratedMessage:
        class: App\Service\SmsDecoratedMessage
        decorates: App\Service\BasicMessageService

    App\Service\FacebookDecoratedMessage:
        class: App\Service\FacebookDecoratedMessage
        decorates: App\Service\SmsDecoratedMessage

    App\Service\SlackDecoratedMessage:
        class: App\Service\SlackDecoratedMessage
        decorates: App\Service\FacebookDecoratedMessage

    # Alias para la interfaz
    App\Service\MessageServiceInterface: '@App\Service\SlackDecoratedMessage'

    App\Service\Tax\TaxContextService:
        class: App\Service\Tax\TaxContextService

    App\Service\Tax\DefaultTaxService:
        class: App\Service\Tax\DefaultTaxService


    App\Service\Tax\TaxColombiaService:
        class: App\Service\Tax\TaxColombiaService

    App\Service\Tax\TaxSpainService:
        class: App\Service\Tax\TaxSpainService
